### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by qwertychouskie** [OliverBurkardt/supertux_music#1]
I want to confirm licensing, the original menu theme is CC-BY-SA 3.0, so any remixes should preferably be released under CC BY-SA 3.0 or 4.0 (updated version of the license).  Currently, there's a GPLv3 license file in the repository, but the GPL is designed for code, and doesn't really apply cleanly to art assets (music/models/textures/etc.)

Does CC BY-SA 4.0 work for you for all the songs contained in this repository? (https://creativecommons.org/licenses/by-sa/4.0/)

**Comment by OliverBurkardt** [comment]
Thank you for the advice.
The songs are now licensed under CC BY-SA 4.0.
